services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ashleylamont/ashl-dev:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`ashl.dev`)"
      - "traefik.http.routers.nuxt.entrypoints=websecure"
      - "traefik.http.services.nuxt.loadbalancer.server.port=3000"
      - "traefik.http.routers.nuxt.tls.certresolver=leresolver"
    networks:
      - traefik_web

networks:
  traefik_web:
    name: traefik_web
    external: true
